name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: DATABASE_URL
        script: |
        echo "🚀 Starting deployment..."
        cd sentiment-analysis-api || exit 1
        echo "📥 Pulling latest code..."
        git pull origin main
        echo "🔧 Setting up environment..."
        source ../sentiment_env/bin/activate
        echo "📦 Installing dependencies..."  
        pip install -r requirements.txt
        echo "🛑 Stopping existing application..."
        sudo pkill -f "python main.py" || true
        sleep 5
        echo "🚀 Starting new application..."
        source ../sentiment_env/bin/activate
        nohup python main.py > api.log 2>&1 &
        echo "⏳ Waiting for application to start..."
        sleep 45
        echo "🔍 Testing application health..."
        curl -f http://localhost:8000/health || exit 1
        echo "🧪 Testing sentiment analysis..."
        curl -X POST "http://localhost:8000/analyze" -H "Content-Type: application/json" -d '{"text": "Deployment successful!"}' || exit 1
        echo "✅ Deployment completed successfully!"